apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: oq02mljzd-go 
  janus-idp.io/tekton: oq02mljzd-go
  backstage.io/kubernetes-id: oq02mljzd-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: oq02mljzd-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  