apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: oq02mljzd-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: oq02mljzd-go 
  name: oq02mljzd-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: oq02mljzd-go 
